{{- if .Values.derp.customRegions -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "headscale.fullname" . }}-derp-regions
  labels:
    {{- include "headscale.labels" . | nindent 4 }}
data:
  custom-regions.yaml: |
    regions:
      {{- range $regionId, $region := .Values.derp.customRegions }}
      {{ $regionId }}:
        {{- $region | toYaml | nindent 8 }}
      {{- end }}
{{- end }}
