{{- if not .Values.keys.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "headscale.fullname" . }}-keys
  labels:
    {{- include "headscale.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.keys.secretKeys.privateKey }}: {{ .Values.keys.privateKey | quote }}
  {{ .Values.keys.secretKeys.noisePrivateKey }}: {{ .Values.keys.noisePrivateKey | quote }}
{{- end }}
