{{- if and .Values.ui.enabled .Values.ui.integration.rbac.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "headscale.fullname" . }}-ui
  labels:
    {{- include "headscale.ui.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "headscale.fullname" . }}-ui
  labels:
    {{- include "headscale.ui.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "configmaps"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["deployments", "replicasets"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "headscale.fullname" . }}-ui
  labels:
    {{- include "headscale.ui.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "headscale.fullname" . }}-ui
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "headscale.fullname" . }}-ui
  apiGroup: rbac.authorization.k8s.io
{{- end }}
