{{- if and .Values.ui.enabled (not .Values.ui.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "headscale.fullname" . }}-ui
  labels:
    {{- include "headscale.ui.labels" . | nindent 4 }}
type: Opaque
stringData:
  api-key: {{ .Values.ui.apiKey | quote }}
  cookie-secret: {{ .Values.ui.cookieSecret | quote }}
{{- end }}
