schedule: "0 7 * * *"

image:
  repository: myregistry/cron-task
  tag: latest

env:
  LOCAL_DAILY_PATH: "/storage/nc_client/daily"
  REMOTE_DAILY_PATH: "nextcloud:/Shared/daily"
  OBSIDIAN_TAG: "#scheduler"
  BOT_TOKEN: "your-bot-token"
  CHAT_ID: "123456789"


resources:
  limits:
    memory: "256Mi"
    cpu: "500m"
  requests:
    memory: "128Mi"
    cpu: "250m"