schedule: "0 7 * * *"

image:
  repository: myregistry/cron-task
  tag: latest

env:
  LOCAL_DAILY_PATH: "/storage/nc_client/daily"
  REMOTE_DAILY_PATH: "nextcloud:/Shared/daily"
  OBSIDIAN_TAG: "#scheduler"
  BOT_TOKEN: "your-bot-token"
  CHAT_ID: "123456789"


resources:
  limits:
    memory: "256Mi"
    cpu: "500m"
  requests:
    memory: "128Mi"
    cpu: "250m"

deployment:
  secret:
    enabled: false
    # base64 encoded value
    app_imagePullSecrets_name: nginx-registry
    app_imagePullSecrets: 
      - name: nginx-registry
    app_dockerconfigjson: "ZXdvSkltRjFkR2h6SWpvZ2V3b0pDU0pvZEhSd2N6b3ZMMmx1WkdWNExtUnZZMnRsY2k1cAo=" # fake secret
