---
{{- if .Values.deployment.secret.enabled -}}
apiVersion: v1
data:
  .dockerconfigjson: {{ .Values.deployment.secret.app_dockerconfigjson }}
kind: Secret
metadata:
  name: {{ .Values.deployment.secret.app_imagePullSecrets_name }}
type: kubernetes.io/dockerconfigjson
{{- end }}
