apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Release.Name }}-task
spec:
  schedule: "{{ .Values.schedule }}"
  successfulJobsHistoryLimit: 5
  failedJobsHistoryLimit: 5
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: cron-task
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
              imagePullPolicy: IfNotPresent
              env:
                - name: LOCAL_DAILY_PATH
                  value: "{{ .Values.env.LOCAL_DAILY_PATH }}"
                - name: REMOTE_DAILY_PATH
                  value: "{{ .Values.env.REMOTE_DAILY_PATH }}"
                - name: OBSIDIAN_TAG
                  value: "{{ .Values.env.OBSIDIAN_TAG }}"
                - name: BOT_TOKEN
                  value: "{{ .Values.env.BOT_TOKEN }}"
                - name: CHAT_ID
                  value: "{{ .Values.env.CHAT_ID }}"
              resources:
                limits:
                  memory: "{{ .Values.resources.limits.memory }}"
                  cpu: "{{ .Values.resources.limits.cpu }}"
                requests:
                  memory: "{{ .Values.resources.requests.memory }}"
                  cpu: "{{ .Values.resources.requests.cpu }}"
          restartPolicy: OnFailure
