apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Release.Name }}-task
spec:
  schedule: "{{ .Values.schedule }}"
  successfulJobsHistoryLimit: 5
  failedJobsHistoryLimit: 5
  jobTemplate:
    spec:
      template:
        spec:
          {{- with .Values.deployment.secret.app_imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 8 }}
          {{- end }}

          containers:
            - name: cron-task
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
              imagePullPolicy: IfNotPresent
              env:
              {{- range $key, $value := .Values.env }}
                - name: {{ $key }}
                  value: "{{ $value }}"
              {{- end }}
              resources:
                limits:
                  memory: "{{ .Values.resources.limits.memory }}"
                  cpu: "{{ .Values.resources.limits.cpu }}"
                requests:
                  memory: "{{ .Values.resources.requests.memory }}"
                  cpu: "{{ .Values.resources.requests.cpu }}"
          restartPolicy: OnFailure
